export const OUTSTATIC_VERSION = '1.4.7'
export const OUTSTATIC_URL = 'https://outstatic.com'
export const IMAGES_PATH = 'images/'
export const API_IMAGES_PATH = 'api/outstatic/images/'
export const GITHUB_GQL_API_URL = 'https://api.github.com/graphql'
