import { defineConfig } from 'tsup'

export default defineConfig({
  entry: [
    'src/lib/utils/index.ts',
    'src/shadcn/alert-dialog.tsx',
    'src/shadcn/breadcrumb.tsx',
    'src/shadcn/button.tsx',
    'src/shadcn/calendar.tsx',
    'src/shadcn/card.tsx',
    'src/shadcn/checkbox.tsx',
    'src/shadcn/command.tsx',
    'src/shadcn/date-time-picker-form.tsx',
    'src/shadcn/dialog.tsx',
    'src/shadcn/form.tsx',
    'src/shadcn/input.tsx',
    'src/shadcn/label.tsx',
    'src/shadcn/popover.tsx',
    'src/shadcn/radio-group.tsx',
    'src/shadcn/scroll-area.tsx',
    'src/shadcn/select.tsx',
    'src/shadcn/skeleton.tsx',
    'src/shadcn/tabs.tsx',
    'src/shadcn/text-area.tsx',
    'src/shadcn/tooltip.tsx',
    'src/lib/utils/index.ts',
    'src/outstatic/search-combobox.tsx',
    'src/outstatic/app-logo.tsx',
    'src/outstatic/checkbox-with-label.tsx',
    'src/outstatic/file-tree.tsx',
    'src/outstatic/github-branch-search.tsx',
    'src/outstatic/github-explorer.tsx',
    'src/outstatic/github-repo-search.tsx',
    'src/outstatic/if.tsx',
    'src/outstatic/line-background.tsx',
    'src/outstatic/loading-background.tsx',
    'src/outstatic/media-library-header.tsx',
    'src/outstatic/media-library-modal.tsx',
    'src/outstatic/media-settings-dialog.tsx',
    'src/outstatic/path-breadcrumb.tsx',
    'src/outstatic/sidebar-footer.tsx',
    'src/outstatic/sidebar.tsx',
    'src/outstatic/spinner-icon.tsx',
    'src/outstatic/stepper.tsx'
  ],
  format: ['esm', 'cjs'],
  dts: true,
  splitting: false,
  sourcemap: true,
  clean: true,
  external: [
    'react',
    'react-dom',
    'next',
    '@radix-ui/*',
    'lucide-react',
    'class-variance-authority',
    'clsx',
    'tailwind-merge',
    'cmdk',
    'date-fns',
    'react-day-picker',
    'react-hook-form',
    'use-resize-observer'
  ],
  treeshake: true,
  minify: true
})
