import { defineConfig } from 'tsup'

export default defineConfig({
  entry: {
    index: 'src/index.tsx',
    // Shadcn components
    'shadcn/alert-dialog': 'src/shadcn/alert-dialog.tsx',
    'shadcn/breadcrumb': 'src/shadcn/breadcrumb.tsx',
    'shadcn/button': 'src/shadcn/button.tsx',
    'shadcn/calendar': 'src/shadcn/calendar.tsx',
    'shadcn/card': 'src/shadcn/card.tsx',
    'shadcn/checkbox': 'src/shadcn/checkbox.tsx',
    'shadcn/command': 'src/shadcn/command.tsx',
    'shadcn/date-time-picker-form': 'src/shadcn/date-time-picker-form.tsx',
    'shadcn/dialog': 'src/shadcn/dialog.tsx',
    'shadcn/form': 'src/shadcn/form.tsx',
    'shadcn/input': 'src/shadcn/input.tsx',
    'shadcn/label': 'src/shadcn/label.tsx',
    'shadcn/popover': 'src/shadcn/popover.tsx',
    'shadcn/radio-group': 'src/shadcn/radio-group.tsx',
    'shadcn/scroll-area': 'src/shadcn/scroll-area.tsx',
    'shadcn/select': 'src/shadcn/select.tsx',
    'shadcn/skeleton': 'src/shadcn/skeleton.tsx',
    'shadcn/tabs': 'src/shadcn/tabs.tsx',
    'shadcn/text-area': 'src/shadcn/text-area.tsx',
    'shadcn/tooltip': 'src/shadcn/tooltip.tsx',
    'lib/utils/index': 'src/lib/utils/index.ts',
    // Outstatic components
    'outstatic/search-combobox': 'src/outstatic/search-combobox.tsx',
    'outstatic/app-logo': 'src/outstatic/app-logo.tsx',
    'outstatic/checkbox-with-label': 'src/outstatic/checkbox-with-label.tsx',
    'outstatic/file-tree': 'src/outstatic/file-tree.tsx',
    'outstatic/if': 'src/outstatic/if.tsx',
    'outstatic/line-background': 'src/outstatic/line-background.tsx',
    'outstatic/loading-background': 'src/outstatic/loading-background.tsx',
    'outstatic/path-breadcrumb': 'src/outstatic/path-breadcrumb.tsx',
    'outstatic/sidebar-footer': 'src/outstatic/sidebar-footer.tsx',
    'outstatic/sidebar': 'src/outstatic/sidebar.tsx',
    'outstatic/spinner-icon': 'src/outstatic/spinner-icon.tsx',
    'outstatic/stepper': 'src/outstatic/stepper.tsx'
  },
  format: ['cjs', 'esm'],
  dts: true,
  clean: true,
  external: [
    'react',
    'react-dom',
    'next',
    '@radix-ui/react-accordion',
    '@radix-ui/react-alert-dialog',
    '@radix-ui/react-checkbox',
    '@radix-ui/react-dialog',
    '@radix-ui/react-label',
    '@radix-ui/react-popover',
    '@radix-ui/react-radio-group',
    '@radix-ui/react-scroll-area',
    '@radix-ui/react-select',
    '@radix-ui/react-slot',
    '@radix-ui/react-tabs',
    '@radix-ui/react-tooltip',
    'clsx',
    'cmdk',
    'lucide-react',
    'tailwind-merge',
    'use-resize-observer',
    'class-variance-authority',
    'date-fns',
    'react-day-picker',
    'react-hook-form'
  ],
  esbuildOptions(options) {
    options.jsx = 'automatic'
  }
})
